### PR TITLE
:bug: Fix Deceleration in LemLib Format V0.4

### PR DESCRIPTION
**Pull request by SizzinSeal**
## Overview
Changes deceleration so it decelerates to the minimum speed, not 0. Only applies to the LemLib v0.4.x format

### CODE REVIEW

**Review by Jerrylum — APPROVED** [review]
I can approve your PR, but do you know you also set the speed of the final point from 0 to `minSpeed`. Are you sure? Did you test it on a robot? I think it should be fine but I still need to confirm it.

Reply this message, I will merge the PR by myself.

**Comment by SizzinSeal** [comment]
Hold on. Let me test this on a LemLib and I'll get back to you

**Comment by SizzinSeal** [comment]
hardware testing successful

**Comment by Jerrylum** [comment]
After the discussion on Discord:
https://discord.com/channels/1118047514269069372/1121114236651851927/1197359943850922097

It is not a bug.

I will merge this PR and modify it.

**Pull request merged**
